"""followers

Revision ID: 669bd4ba3d4e
Revises: 268e696655bb
Create Date: 2020-06-18 23:04:48.670921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669bd4ba3d4e'
down_revision = '268e696655bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
